### ISSUE TITLE
Reporte de entrevista

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-promastergamer777#2]
Subir reporte

**Comment by FedericoVictorianoSierra** [comment]
[Informe de entrevista (FEDERICO VICTORIANO SIERRA).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-promastergamer777/files/12516402/Informe.de.entrevista.FEDERICO.VICTORIANO.SIERRA.pdf)

**Comment by JoseABCruz** [comment]
[Informe de entrevista (José Antonio Balbuena Cruz 7US).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-promastergamer777/files/12516400/Informe.de.entrevista.Jose.Antonio.Balbuena.Cruz.7US.pdf)

**Comment by Heidi-19** [comment]
[Informe de entrevista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-promastergamer777/files/12516415/Informe.de.entrevista.pdf)

**Comment by bg55-a** [comment]
calificacion:20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
